### ISSUE TITLE
Coding style and indentations

### ISSUE THREAD

**Issue by mamal72** [morajabi/rc-classnames#2]
Hey. I just read some parts of your code and I saw an issue.
The style of this code is not good enough. There are random indentations in the code (spaces and tabs) and some parts are not indented as they should.

The code should be beautiful and easy to read. I highly recommend you to use a linter like [ESLint](http://eslint.org).

**Comment by morajabi** [comment]
I edited code and added ESLint with JSStandard config to project. I think It's easier to read and better. If you have any other suggestion, PRs welcome!

**Comment by morajabi** [comment]
I think It's OK to close this issue now.

**Comment by mamal72** [comment]
@morajabi That's far better now. Following a coding style is up to the maintainer but personally, I don't like Standard style. It's not really **Standard** and the name is confusing users IMO. Also, I'm a huge fan of semicolons in JS.
Anyway, it's up to you and I can't decide. It's always good to follow a pattern and so, it's good! 😁

**Comment by morajabi** [comment]
I'm not a huge fan of semi-colons but I like them. I didn't have time to configure ESLint by hand so I saw JSStandard Style configuration and I decided to use it. I don't think It's important to **have** semi-colons or **not** for a less-than 50 line  library!
